export const TEMPLATES = {
  Viral: {
    card: "bg-black border border-purple-500/40",
    title: "text-white font-black text-3xl tracking-tight",
    desc: "text-zinc-400",
    dot: "bg-pink-400 shadow-[0_0_12px_#f472b6]",
    num: "text-purple-300",
    isLight: false,
  },
  Storytelling: {
    card: "bg-gradient-to-br from-fuchsia-900/40 to-black border border-fuchsia-500/30",
    title: "text-white font-black text-3xl italic",
    desc: "text-zinc-300",
    dot: "bg-pink-400 shadow-[0_0_12px_#f472b6]",
    num: "text-fuchsia-300",
    isLight: false,
  },
  Minimal: {
    card: "bg-zinc-950 border border-white/10",
    title: "text-white font-bold text-3xl",
    desc: "text-zinc-500",
    dot: "bg-white",
    num: "text-zinc-500",
    isLight: false,
  },
  Corporate: {
    card: "bg-blue-950 border border-blue-400/20",
    title: "text-white font-extrabold text-3xl uppercase",
    desc: "text-blue-100",
    dot: "bg-cyan-400 shadow-[0_0_12px_#22d3ee]",
    num: "text-cyan-300",
    isLight: false,
  },
  Light: {
    card: "bg-white border border-gray-100",
    title: "text-gray-900 font-black text-3xl tracking-tight",
    desc: "text-gray-500",
    dot: "bg-purple-500",
    num: "text-gray-300",
    isLight: true,
  },
  Gradient: {
    card: "bg-gradient-to-br from-violet-600 to-indigo-600 border-0",
    title: "text-white font-black text-3xl",
    desc: "text-white/70",
    dot: "bg-yellow-300 shadow-[0_0_12px_#fde047]",
    num: "text-white/30",
    isLight: false,
  },
  Bold: {
    card: "bg-yellow-400 border-0",
    title: "text-black font-black text-3xl uppercase tracking-tighter",
    desc: "text-black/60",
    dot: "bg-black",
    num: "text-black/20",
    isLight: true,
  },
  Neon: {
    card: "bg-black border border-green-400/30",
    title: "text-green-400 font-black text-3xl",
    desc: "text-green-200/60",
    dot: "bg-green-400 shadow-[0_0_12px_#4ade80]",
    num: "text-green-700",
    isLight: false,
  },
  Linear: {
    card: "bg-[#08090c] border border-white/[0.07]",
    title: "text-white font-semibold text-3xl tracking-tight",
    desc: "text-zinc-400",
    dot: "bg-violet-500 shadow-[0_0_10px_rgba(139,92,246,0.5)]",
    num: "text-zinc-500",
    isLight: false,
  },
  Stripe: {
    card: "bg-gradient-to-br from-[#f6f9fc] to-[#eef1f6] border border-black/5",
    title: "text-slate-900 font-semibold text-3xl tracking-tight",
    desc: "text-slate-500",
    dot: "bg-indigo-500 shadow-[0_0_10px_rgba(99,102,241,0.5)]",
    num: "text-slate-400",
    isLight: true,
  },
  Raycast: {
    card: "bg-black border border-white/[0.08]",
    title: "text-white font-semibold text-3xl tracking-tight",
    desc: "text-zinc-400",
    dot: "bg-red-500 shadow-[0_0_10px_rgba(239,68,68,0.5)]",
    num: "text-red-400",
    isLight: false,
  },
  Midnight: {
    card: "bg-[#0d1117] border border-cyan-500/20",
    title: "text-white font-bold text-3xl tracking-tight",
    desc: "text-slate-400",
    dot: "bg-cyan-400 shadow-[0_0_10px_rgba(34,211,238,0.5)]",
    num: "text-cyan-600",
    isLight: false,
  },
  Rose: {
    card: "bg-gradient-to-br from-rose-50 to-pink-100 border border-rose-200/60",
    title: "text-rose-950 font-black text-3xl tracking-tight",
    desc: "text-rose-700/70",
    dot: "bg-rose-500",
    num: "text-rose-300",
    isLight: true,
  },
  Forest: {
    card: "bg-[#0a1a0e] border border-emerald-500/20",
    title: "text-emerald-50 font-bold text-3xl",
    desc: "text-emerald-400/70",
    dot: "bg-emerald-400 shadow-[0_0_10px_rgba(52,211,153,0.5)]",
    num: "text-emerald-800",
    isLight: false,
  },
  Amber: {
    card: "bg-amber-50 border border-amber-200",
    title: "text-amber-950 font-black text-3xl uppercase tracking-tight",
    desc: "text-amber-800/70",
    dot: "bg-amber-500",
    num: "text-amber-300",
    isLight: true,
  },
  Slate: {
    card: "bg-gradient-to-b from-slate-700 to-slate-900 border border-slate-600/30",
    title: "text-white font-extrabold text-3xl",
    desc: "text-slate-300",
    dot: "bg-sky-400 shadow-[0_0_10px_rgba(56,189,248,0.5)]",
    num: "text-slate-500",
    isLight: false,
  },
  Ocean: {
    card: "bg-gradient-to-br from-blue-600 to-cyan-500 border-0",
    title: "text-white font-black text-3xl tracking-tight",
    desc: "text-white/75",
    dot: "bg-white shadow-[0_0_10px_rgba(255,255,255,0.5)]",
    num: "text-white/30",
    isLight: false,
  },
  Paper: {
    card: "bg-[#faf8f5] border border-stone-200",
    title: "text-stone-900 font-bold text-3xl tracking-tight",
    desc: "text-stone-500",
    dot: "bg-orange-400",
    num: "text-stone-300",
    isLight: true,
  },
  Carbon: {
    card: "bg-[#111111] border border-orange-500/25",
    title: "text-white font-black text-3xl tracking-tighter",
    desc: "text-zinc-500",
    dot: "bg-orange-500 shadow-[0_0_10px_rgba(249,115,22,0.5)]",
    num: "text-orange-700",
    isLight: false,
  },
  Notion: {
    card: "bg-[#191919] border border-white/[0.06]",
    title: "text-white font-bold text-3xl tracking-tight",
    desc: "text-zinc-400",
    dot: "bg-zinc-400",
    num: "text-zinc-600",
    isLight: false,
  },
  Chalk: {
    card: "bg-white border border-gray-200",
    title: "text-gray-900 font-bold text-3xl tracking-tight",
    desc: "text-gray-400",
    dot: "bg-gray-900",
    num: "text-gray-200",
    isLight: true,
  },
  Ruby: {
    card: "bg-[#0d0608] border border-red-500/20",
    title: "text-white font-black text-3xl tracking-tight",
    desc: "text-red-200/60",
    dot: "bg-red-500 shadow-[0_0_10px_rgba(239,68,68,0.5)]",
    num: "text-red-900",
    isLight: false,
  },
  Cream: {
    card: "bg-[#fffdf7] border border-amber-100",
    title: "text-gray-900 font-serif font-bold text-3xl",
    desc: "text-stone-500",
    dot: "bg-amber-400",
    num: "text-amber-200",
    isLight: true,
  },
  Framer: {
    card: "bg-gradient-to-br from-[#1a0533] to-[#0d0117] border border-purple-500/20",
    title: "text-white font-semibold text-3xl tracking-tight",
    desc: "text-purple-200/60",
    dot: "bg-purple-400 shadow-[0_0_10px_rgba(192,132,252,0.6)]",
    num: "text-purple-700",
    isLight: false,
  },
  Infographic: {
    card: "bg-white border-l-4 border-l-blue-600 border-t border-r border-b border-gray-100",
    title: "text-blue-900 font-black text-3xl uppercase tracking-tight",
    desc: "text-gray-600",
    dot: "bg-blue-600",
    num: "text-blue-200",
    isLight: true,
  },
} as const;

export type TemplateKey = keyof typeof TEMPLATES;

export const TONES = ["Storytelling", "Authority", "Contrarian", "Data-Driven"] as const;
export type ToneKey = (typeof TONES)[number];

export const SHOWCASE_EXAMPLES: { style: TemplateKey; title: string; desc: string }[] = [
  {
    style: "Viral",
    title: "I Quit My 9-to-5 to Build This",
    desc: "Everyone said I was crazy. Six months later, this side project pays my rent. Here's exactly what changed.",
  },
  {
    style: "Stripe",
    title: "3 Metrics Every Founder Should Track",
    desc: "Most founders obsess over vanity metrics. These three numbers actually predict whether your startup survives.",
  },
  {
    style: "Linear",
    title: "Why Most Startups Get Positioning Wrong",
    desc: "You're not competing on features. You're competing on a single sentence in your customer's head.",
  },
  {
    style: "Gradient",
    title: "The LinkedIn Algorithm Just Changed",
    desc: "Reach dropped 40% overnight for most creators. Here's what's actually working in the new feed.",
  },
];

export const IDEA_BANK: { category: string; idea: string }[] = [
  { category: "Career", idea: "How I negotiated a 30% raise without changing jobs" },
  { category: "Career", idea: "The interview answer that got me hired everywhere I applied" },
  { category: "Career", idea: "Why I stopped chasing promotions and started building skills" },
  { category: "Founder", idea: "The biggest mistake I made in my first year as a founder" },
  { category: "Founder", idea: "How we got our first 100 customers without spending on ads" },
  { category: "Founder", idea: "Why I turned down funding and bootstrapped instead" },
  { category: "Productivity", idea: "The 2-hour rule that doubled my output" },
  { category: "Productivity", idea: "Why multitasking was making me less productive" },
  { category: "Productivity", idea: "How I cut my meetings in half and got more done" },
  { category: "Marketing", idea: "Why your LinkedIn posts aren't getting engagement" },
  { category: "Marketing", idea: "The content framework that 10x'd my reach in 30 days" },
  { category: "Marketing", idea: "What I learned from analyzing 100 viral LinkedIn posts" },
  { category: "Leadership", idea: "The management mistake that cost me my best employee" },
  { category: "Leadership", idea: "How I learned to give feedback people actually act on" },
  { category: "Leadership", idea: "Why I stopped trying to be liked and started leading" },
];
